In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/heart-disease-prediction-dataset/Heart_Disease_Prediction.csv

In [2]:
from sklearn.tree import DecisionTreeClassifier,export_graphviz
import graphviz
from sklearn.model_selection import train_test_split

In [3]:
df = pd.read_csv('/kaggle/input/heart-disease-prediction-dataset/Heart_Disease_Prediction.csv')
df.head(3)

,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium,Heart Disease
0,70,1,4,130,322,0,2,109,0,2.4,2,3,3,Presence
1,67,0,3,115,564,0,2,160,0,1.6,2,0,7,Absence
2,57,1,2,124,261,0,0,141,0,0.3,1,0,7,Presence

In [4]:
df = pd.get_dummies(df , columns = ['Heart Disease'] , drop_first = True , dtype = int)

In [5]:
df.head(3)

,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium,Heart Disease_Presence
0,70,1,4,130,322,0,2,109,0,2.4,2,3,3,1
1,67,0,3,115,564,0,2,160,0,1.6,2,0,7,0
2,57,1,2,124,261,0,0,141,0,0.3,1,0,7,1

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 270 entries, 0 to 269
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Age                      270 non-null    int64
 1   Sex                      270 non-null    int64
 2   Chest pain type          270 non-null    int64
 3   BP                       270 non-null    int64
 4   Cholesterol              270 non-null    int64
 5   FBS over 120             270 non-null    int64
 6   EKG results              270 non-null    int64
 7   Max HR                   270 non-null    int64
 8   Exercise angina          270 non-null    int64
 9   ST depression            270 non-null    float64
 10  Slope of ST              270 non-null    int64
 11  Number of vessels fluro  270 non-null    int64
 12  Thallium                 270 non-null    int64
 13  Heart Disease_Presence   270 non-null    int64
dtypes: float64(1), int64(13)
memory usage: 29.7 KB

In [7]:
y = df['Heart Disease_Presence']
x = df.drop(columns = ['Heart Disease_Presence'] , axis = 1)

In [8]:
x_train , x_test , y_train , y_test = train_test_split(x,y, test_size = 0.3 , random_state = 6)

In [9]:
tree = DecisionTreeClassifier()

In [10]:
model = tree.fit(x_train,y_train)
model.score(x_test , y_test)

0.7283950617283951

In [11]:
model.predict([[31,1,2,130,240,0,0,150,0,2,0,0,2]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([0])

In [12]:
from sklearn.ensemble import RandomForestClassifier
forest = RandomForestClassifier()
model = forest.fit(x,y)
model.score(x,y)

1.0

In [13]:
forest = RandomForestClassifier(n_estimators = 300 , max_depth=4, criterion = 'entropy')
model = forest.fit(x_train , y_train)
model.score(x_test,y_test)

0.8888888888888888