In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/insurance/insurance.csv

In [2]:
df = pd.read_csv('/kaggle/input/insurance/insurance.csv')
df.head(3)

   age     sex    bmi  children smoker     region     charges
0   19  female  27.90         0    yes  southwest  16884.9240
1   18    male  33.77         1     no  southeast   1725.5523
2   28    male  33.00         3     no  southeast   4449.4620

In [3]:
df.shape

(1338, 7)

In [4]:
df.sample()

     age   sex     bmi  children smoker     region     charges
657   27  male  33.155         2     no  northwest  4058.71245

In [5]:
df = pd.get_dummies(df , columns = ['sex' , 'smoker' , 'region'] , drop_first = True , dtype = int)

In [6]:
df.head(3)

,age,bmi,children,charges,sex_male,smoker_yes,region_northwest,region_southeast,region_southwest
0,19,27.90,0,16884.9240,0,1,0,0,1
1,18,33.77,1,1725.5523,1,0,0,1,0
2,28,33.00,3,4449.4620,1,0,0,1,0

In [7]:
y = df['charges']
x = df.drop(columns = ['charges'] , axis = 1)

In [8]:
x_train , x_test , y_train , y_test  =train_test_split(x , y ,test_size = 0.3 , random_state = 22)

In [9]:
lr = LinearRegression()
model = lr.fit(x_train , y_train)
model.score(x_test , y_test)

0.7398405242767803

In [10]:
rf = RandomForestRegressor(n_estimators = 200)
model = rf.fit(x_train , y_train)
model.score(x_test , y_test)

0.8272952313017546

In [11]:
x.head(3)

,age,bmi,children,sex_male,smoker_yes,region_northwest,region_southeast,region_southwest
0,19,27.90,0,0,1,0,0,1
1,18,33.77,1,1,0,0,1,0
2,28,33.00,3,1,0,0,1,0

In [12]:
model.predict([[31,27.4,0,1,1,1,0,0]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(

array([18787.01855575])