In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/insurance/insurance.csv

In [2]:
df = pd.read_csv('/kaggle/input/insurance/insurance.csv')
df.head(3)

   age     sex    bmi  children smoker     region     charges
0   19  female  27.90         0    yes  southwest  16884.9240
1   18    male  33.77         1     no  southeast   1725.5523
2   28    male  33.00         3     no  southeast   4449.4620

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   object
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   object
 5   region    1338 non-null   object
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB

In [4]:
df = pd.get_dummies(df , columns = ['sex' , 'smoker' , 'region'] , drop_first = True , dtype = int)
df.head(3)

,age,bmi,children,charges,sex_male,smoker_yes,region_northwest,region_southeast,region_southwest
0,19,27.90,0,16884.9240,0,1,0,0,1
1,18,33.77,1,1725.5523,1,0,0,1,0
2,28,33.00,3,4449.4620,1,0,0,1,0

In [5]:
y = df['charges']
x = df.drop(columns = ['charges'] , axis =1)

In [6]:
x.head(3)

,age,bmi,children,sex_male,smoker_yes,region_northwest,region_southeast,region_southwest
0,19,27.90,0,0,1,0,0,1
1,18,33.77,1,1,0,0,1,0
2,28,33.00,3,1,0,0,1,0

In [7]:
y.head(3)

0    16884.9240
1     1725.5523
2     4449.4620
Name: charges, dtype: float64

In [8]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(x , y ,test_size = 0.3 , random_state = 6)

In [9]:
from sklearn.linear_model import LinearRegression
lm = LinearRegression()
model = lm.fit(x_train , y_train)
model_pred = model.predict(x_test)

In [10]:
df_pred = pd.DataFrame()
df_pred['y_test'] = y_test

In [11]:
df_pred['pred'] = model_pred

In [12]:
df_pred.head(3)

          y_test          pred
811   6360.99360  12569.697551
973   1759.33800   5720.169630
308  11944.59435  15130.786311

In [13]:
model.score(x_test , y_test)

0.7717480441348381

In [14]:
from sklearn.metrics import mean_squared_error , mean_absolute_error , mean_absolute_percentage_error

In [15]:
mean_squared_error(y_test,model_pred)

31439669.90965587

In [16]:
mean_absolute_error(y_test,model_pred)

4030.0746914291444

In [17]:
mean_absolute_percentage_error(y_test,model_pred)

0.4311115064917078