In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/mobil-bankaclk-sesli-komut-veri-seti-trke/yenibanka.csv
/kaggle/input/mobil-bankaclk-sesli-komut-veri-seti-trke/banka.csv

In [2]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

In [3]:
df = pd.read_csv('/kaggle/input/mobil-bankaclk-sesli-komut-veri-seti-trke/banka.csv')
df.head()

                                      metin                 kategori
0        kart şifremi değiştirmek istiyorum  Kart Şifresi Değiştirme
1  kartımın şifresini değiştirmek istiyorum  Kart Şifresi Değiştirme
2          kredi kartımın şifresini unuttum  Kart Şifresi Değiştirme
3               kart şifremi hatırlamıyorum  Kart Şifresi Değiştirme
4              kart şifresi almak istiyorum  Kart Şifresi Değiştirme

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1160 entries, 0 to 1159
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   metin     1160 non-null   object
 1   kategori  1160 non-null   object
dtypes: object(2)
memory usage: 18.3+ KB

In [5]:
df.head(3)

                                      metin                 kategori
0        kart şifremi değiştirmek istiyorum  Kart Şifresi Değiştirme
1  kartımın şifresini değiştirmek istiyorum  Kart Şifresi Değiştirme
2          kredi kartımın şifresini unuttum  Kart Şifresi Değiştirme

In [6]:
df['kategori'] = df['kategori'].str.lower()

In [7]:
df.head()

                                      metin                 kategori
0        kart şifremi değiştirmek istiyorum  kart şifresi değiştirme
1  kartımın şifresini değiştirmek istiyorum  kart şifresi değiştirme
2          kredi kartımın şifresini unuttum  kart şifresi değiştirme
3               kart şifremi hatırlamıyorum  kart şifresi değiştirme
4              kart şifresi almak istiyorum  kart şifresi değiştirme

In [8]:

stopwords=['fakat','lakin','ancak','acaba', 'ama', 'aslında', 'az', 'bazı', 'belki', 'biri', 'birkaç', 'birşey', 'biz', 'bu', 'çok', 'çünkü', 'da', 'daha', 'de', 'defa', 'diye', 'eğer', 'en', 'gibi', 'hem', 'hep', 'hepsi', 'her', 'hiç', 'için', 'ile', 'ise', 'kez', 'ki', 'kim', 'mı', 'mu', 'mü', 'nasıl', 'ne', 'neden', 'nerde', 'nerede', 'nereye', 'niçin', 'niye', 'o', 'sanki', 'şey', 'siz', 'şu', 'tüm', 've', 'veya', 'ya', 'yani']

mesaj=input("Yapmak İstediniz İşlemi Giriniz.")

mesajdf=pd.DataFrame({"metin":mesaj,"kategori":0},index=[42])

df=pd.concat([df,mesajdf],ignore_index=True)



for word in stopwords:
    word=" "+word+" "
    df['metin']=df['metin'].str.replace(word," ")

cv=CountVectorizer(max_features=50)


x=cv.fit_transform(df['metin']).toarray()
y=df['kategori']


tahmin=x[-1].copy()

x=x[0:-1]
y=y[0:-1]

x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=21,train_size=0.7)

rf=RandomForestClassifier()
model=rf.fit(x_train,y_train)
skor=model.score(x_test,y_test)

sonuc=model.predict([tahmin])

print("Sonuc:",sonuc,"Skor:",skor)

StdinNotImplementedError: raw_input was called, but this frontend does not support input requests.