In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/titanic/train.csv
/kaggle/input/titanic/test.csv
/kaggle/input/titanic/gender_submission.csv

In [2]:
train_df = pd.read_csv('/kaggle/input/titanic/train.csv')
train_df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [3]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [4]:
train_df = train_df.drop(columns = ['PassengerId' , 'Name' , 'Ticket' , 'Cabin'] , axis = 1)
train_df.head(3)

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S

In [5]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
 1   Pclass    891 non-null    int64
 2   Sex       891 non-null    object
 3   Age       714 non-null    float64
 4   SibSp     891 non-null    int64
 5   Parch     891 non-null    int64
 6   Fare      891 non-null    float64
 7   Embarked  889 non-null    object
dtypes: float64(2), int64(4), object(2)
memory usage: 55.8+ KB

In [6]:
# Yaş sütunundaki boşlukları medyan değer ile dolduruyoruz
train_df['Age'] = train_df['Age'].fillna(train_df['Age'].median())
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
 1   Pclass    891 non-null    int64
 2   Sex       891 non-null    object
 3   Age       891 non-null    float64
 4   SibSp     891 non-null    int64
 5   Parch     891 non-null    int64
 6   Fare      891 non-null    float64
 7   Embarked  889 non-null    object
dtypes: float64(2), int64(4), object(2)
memory usage: 55.8+ KB

In [7]:
# En sık biniş yapılan limanı bulup (genelde 'S') boşluklara yazıyoruz
most_freq_port = train_df['Embarked'].mode()[0]
train_df['Embarked'] = train_df['Embarked'].fillna(most_freq_port)

In [8]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
 1   Pclass    891 non-null    int64
 2   Sex       891 non-null    object
 3   Age       891 non-null    float64
 4   SibSp     891 non-null    int64
 5   Parch     891 non-null    int64
 6   Fare      891 non-null    float64
 7   Embarked  891 non-null    object
dtypes: float64(2), int64(4), object(2)
memory usage: 55.8+ KB

In [9]:
train_df = pd.get_dummies(train_df , columns = ['Sex' , 'Embarked'] , drop_first = True , dtype = int)
train_df.head(3)

,Survived,Pclass,Age,SibSp,Parch,Fare,Sex_male,Embarked_Q,Embarked_S
0,0,3,22.0,1,0,7.2500,1,0,1
1,1,1,38.0,1,0,71.2833,0,0,0
2,1,3,26.0,0,0,7.9250,0,0,1

In [10]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Survived    891 non-null    int64
 1   Pclass      891 non-null    int64
 2   Age         891 non-null    float64
 3   SibSp       891 non-null    int64
 4   Parch       891 non-null    int64
 5   Fare        891 non-null    float64
 6   Sex_male    891 non-null    int64
 7   Embarked_Q  891 non-null    int64
 8   Embarked_S  891 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 62.8 KB

In [11]:
y = train_df['Survived']
x = train_df.drop(columns = ['Survived'] , axis = 1)

In [12]:
from sklearn.model_selection import train_test_split
x_train , x_val , y_train , y_val = train_test_split(x ,y , test_size = 0.2 , random_state = 22)

In [13]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
x_train_ss = ss.fit_transform(x_train)
x_val_ss = ss.transform(x_val)

In [14]:
x_train_ss.shape[1]

8

In [15]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout

# 1. Model Mimarisi Oluşturma
model = Sequential([
    # Giriş Katmanı ve İlk Gizli Katman (16 nöron)
    # input_shape=(8,) çünkü X_train_ss içinde 8 sütun var
    Dense(16, activation='relu', input_shape=(x_train_ss.shape[1],)),
    
    # İkinci Gizli Katman (8 nöron)
    Dense(8, activation='relu'),
    
    # Dropout (Ezberlemeyi -Overfitting- önlemek için %20'sini kapatıyoruz)
    Dropout(0.2),
    # Çıkış Katmanı (Tek nöron: 0 veya 1 tahmini için Sigmoid kullanılır)
    Dense(1, activation='sigmoid')
])

# 2. Modeli Derleme (Compile)
model.compile(optimizer='adam', 
              loss='binary_crossentropy', 
              metrics=['accuracy'])

# 3. Eğitim (Fit)
# validation_data kısmına ayırdığın val setini veriyoruz
history = model.fit(x_train_ss, y_train, 
                    epochs=100, 
                    batch_size=32, 
                    validation_data=(x_val_ss, y_val),
                    verbose=1)

2026-02-09 18:23:38.569508: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1770661418.774831      17 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1770661418.836190      17 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1770661419.303313      17 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1770661419.303352      17 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1770661419.303356      17 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1770661419.303358      17 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.

Epoch 1/100

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
2026-02-09 18:23:50.763902: E external/local_xla/xla/stream_executor/cuda/cuda_platform.cc:51] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)

23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.6132 - loss: 0.6675 - val_accuracy: 0.6927 - val_loss: 0.6119
Epoch 2/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6444 - loss: 0.6257 - val_accuracy: 0.7151 - val_loss: 0.5813
Epoch 3/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6775 - loss: 0.6011 - val_accuracy: 0.7486 - val_loss: 0.5587
Epoch 4/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7305 - loss: 0.5613 - val_accuracy: 0.7542 - val_loss: 0.5404
Epoch 5/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7321 - loss: 0.5522 - val_accuracy: 0.7765 - val_loss: 0.5254
Epoch 6/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7390 - loss: 0.5497 - val_accuracy: 0.7877 - val_loss: 0.5123
Epoch 7/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7856 - loss: 0.5062 - val_accuracy: 0.7933 - val_loss: 0.4999
Epoch 8/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7896 - loss: 0.4945 - val_accuracy: 0.7989 - val_loss: 0.4925
Epoch 9/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7656 - loss: 0.4950 - val_accuracy: 0.7821 - val_loss: 0.4871
Epoch 10/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8200 - loss: 0.4499 - val_accuracy: 0.7877 - val_loss: 0.4838
Epoch 11/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8187 - loss: 0.4345 - val_accuracy: 0.7989 - val_loss: 0.4811
Epoch 12/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8170 - loss: 0.4434 - val_accuracy: 0.7989 - val_loss: 0.4789
Epoch 13/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8051 - loss: 0.4627 - val_accuracy: 0.7765 - val_loss: 0.4768
Epoch 14/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8135 - loss: 0.4416 - val_accuracy: 0.7877 - val_loss: 0.4733
Epoch 15/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7807 - loss: 0.4986 - val_accuracy: 0.7709 - val_loss: 0.4725
Epoch 16/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7998 - loss: 0.4491 - val_accuracy: 0.7709 - val_loss: 0.4702
Epoch 17/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7963 - loss: 0.4590 - val_accuracy: 0.7709 - val_loss: 0.4705
Epoch 18/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8056 - loss: 0.4120 - val_accuracy: 0.7933 - val_loss: 0.4688
Epoch 19/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8115 - loss: 0.4396 - val_accuracy: 0.7709 - val_loss: 0.4712
Epoch 20/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7818 - loss: 0.4416 - val_accuracy: 0.7709 - val_loss: 0.4713
Epoch 21/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8080 - loss: 0.4232 - val_accuracy: 0.7765 - val_loss: 0.4717
Epoch 22/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7972 - loss: 0.4390 - val_accuracy: 0.7765 - val_loss: 0.4687
Epoch 23/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8094 - loss: 0.4226 - val_accuracy: 0.7765 - val_loss: 0.4694
Epoch 24/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8404 - loss: 0.4073 - val_accuracy: 0.7765 - val_loss: 0.4699
Epoch 25/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8317 - loss: 0.4194 - val_accuracy: 0.7765 - val_loss: 0.4702
Epoch 26/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7783 - loss: 0.4630 - val_accuracy: 0.7765 - val_loss: 0.4707
Epoch 27/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8195 - loss: 0.4100 - val_accuracy: 0.7765 - val_loss: 0.4706
Epoch 28/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8225 - loss: 0.3949 - val_accuracy: 0.7821 - val_loss: 0.4696
Epoch 29/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8164 - loss: 0.4167 - val_accuracy: 0.7821 - val_loss: 0.4689
Epoch 30/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8239 - loss: 0.3991 - val_accuracy: 0.7765 - val_loss: 0.4692
Epoch 31/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8500 - loss: 0.4129 - val_accuracy: 0.7709 - val_loss: 0.4689
Epoch 32/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8339 - loss: 0.3822 - val_accuracy: 0.7765 - val_loss: 0.4690
Epoch 33/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8267 - loss: 0.3855 - val_accuracy: 0.7821 - val_loss: 0.4704
Epoch 34/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8298 - loss: 0.4056 - val_accuracy: 0.7709 - val_loss: 0.4707
Epoch 35/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8339 - loss: 0.3987 - val_accuracy: 0.7598 - val_loss: 0.4707
Epoch 36/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8141 - loss: 0.4098 - val_accuracy: 0.7765 - val_loss: 0.4691
Epoch 37/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8444 - loss: 0.3888 - val_accuracy: 0.7765 - val_loss: 0.4678
Epoch 38/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8103 - loss: 0.4335 - val_accuracy: 0.7765 - val_loss: 0.4672
Epoch 39/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7942 - loss: 0.4461 - val_accuracy: 0.7709 - val_loss: 0.4693
Epoch 40/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8179 - loss: 0.4036 - val_accuracy: 0.7877 - val_loss: 0.4683
Epoch 41/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8267 - loss: 0.3846 - val_accuracy: 0.7765 - val_loss: 0.4686
Epoch 42/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8315 - loss: 0.4089 - val_accuracy: 0.7821 - val_loss: 0.4703
Epoch 43/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8217 - loss: 0.3970 - val_accuracy: 0.7821 - val_loss: 0.4697
Epoch 44/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8412 - loss: 0.4065 - val_accuracy: 0.7765 - val_loss: 0.4700
Epoch 45/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8258 - loss: 0.4272 - val_accuracy: 0.7765 - val_loss: 0.4726
Epoch 46/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8192 - loss: 0.4137 - val_accuracy: 0.7821 - val_loss: 0.4713
Epoch 47/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8175 - loss: 0.3997 - val_accuracy: 0.7821 - val_loss: 0.4725
Epoch 48/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8227 - loss: 0.3942 - val_accuracy: 0.7821 - val_loss: 0.4721
Epoch 49/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8316 - loss: 0.3880 - val_accuracy: 0.7765 - val_loss: 0.4739
Epoch 50/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8155 - loss: 0.4087 - val_accuracy: 0.7821 - val_loss: 0.4727
Epoch 51/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8349 - loss: 0.3725 - val_accuracy: 0.7821 - val_loss: 0.4719
Epoch 52/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8298 - loss: 0.3900 - val_accuracy: 0.7821 - val_loss: 0.4712
Epoch 53/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8098 - loss: 0.4194 - val_accuracy: 0.7989 - val_loss: 0.4690
Epoch 54/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8299 - loss: 0.4003 - val_accuracy: 0.8045 - val_loss: 0.4694
Epoch 55/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8272 - loss: 0.3858 - val_accuracy: 0.8156 - val_loss: 0.4670
Epoch 56/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8309 - loss: 0.3857 - val_accuracy: 0.7933 - val_loss: 0.4711
Epoch 57/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8192 - loss: 0.4142 - val_accuracy: 0.7989 - val_loss: 0.4710
Epoch 58/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8390 - loss: 0.4097 - val_accuracy: 0.7765 - val_loss: 0.4737
Epoch 59/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8285 - loss: 0.3908 - val_accuracy: 0.7877 - val_loss: 0.4730
Epoch 60/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8641 - loss: 0.3626 - val_accuracy: 0.7877 - val_loss: 0.4734
Epoch 61/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8300 - loss: 0.3858 - val_accuracy: 0.7709 - val_loss: 0.4785
Epoch 62/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8172 - loss: 0.4133 - val_accuracy: 0.7821 - val_loss: 0.4777
Epoch 63/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8407 - loss: 0.3687 - val_accuracy: 0.7877 - val_loss: 0.4776
Epoch 64/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8302 - loss: 0.3927 - val_accuracy: 0.7821 - val_loss: 0.4793
Epoch 65/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8323 - loss: 0.3885 - val_accuracy: 0.7821 - val_loss: 0.4792
Epoch 66/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8165 - loss: 0.3855 - val_accuracy: 0.7933 - val_loss: 0.4763
Epoch 67/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8354 - loss: 0.3927 - val_accuracy: 0.7821 - val_loss: 0.4746
Epoch 68/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8460 - loss: 0.3580 - val_accuracy: 0.7933 - val_loss: 0.4767
Epoch 69/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8315 - loss: 0.3821 - val_accuracy: 0.7933 - val_loss: 0.4742
Epoch 70/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8374 - loss: 0.3689 - val_accuracy: 0.7933 - val_loss: 0.4747
Epoch 71/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7969 - loss: 0.4135 - val_accuracy: 0.7877 - val_loss: 0.4744
Epoch 72/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8262 - loss: 0.4033 - val_accuracy: 0.7821 - val_loss: 0.4754
Epoch 73/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8594 - loss: 0.3602 - val_accuracy: 0.7821 - val_loss: 0.4754
Epoch 74/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8247 - loss: 0.3889 - val_accuracy: 0.7821 - val_loss: 0.4713
Epoch 75/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8356 - loss: 0.3803 - val_accuracy: 0.7877 - val_loss: 0.4713
Epoch 76/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7981 - loss: 0.4254 - val_accuracy: 0.7933 - val_loss: 0.4709
Epoch 77/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8154 - loss: 0.4025 - val_accuracy: 0.7989 - val_loss: 0.4716
Epoch 78/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8187 - loss: 0.4107 - val_accuracy: 0.7877 - val_loss: 0.4749
Epoch 79/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8220 - loss: 0.3931 - val_accuracy: 0.7877 - val_loss: 0.4757
Epoch 80/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8208 - loss: 0.3971 - val_accuracy: 0.7821 - val_loss: 0.4766
Epoch 81/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8347 - loss: 0.3996 - val_accuracy: 0.7877 - val_loss: 0.4745
Epoch 82/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8221 - loss: 0.3906 - val_accuracy: 0.7821 - val_loss: 0.4743
Epoch 83/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8180 - loss: 0.3766 - val_accuracy: 0.7877 - val_loss: 0.4741
Epoch 84/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8265 - loss: 0.3745 - val_accuracy: 0.7821 - val_loss: 0.4758
Epoch 85/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8419 - loss: 0.3959 - val_accuracy: 0.7821 - val_loss: 0.4740
Epoch 86/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8384 - loss: 0.3822 - val_accuracy: 0.7877 - val_loss: 0.4751
Epoch 87/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8400 - loss: 0.3867 - val_accuracy: 0.7877 - val_loss: 0.4714
Epoch 88/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8180 - loss: 0.4094 - val_accuracy: 0.7877 - val_loss: 0.4708
Epoch 89/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8427 - loss: 0.3916 - val_accuracy: 0.7821 - val_loss: 0.4701
Epoch 90/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8247 - loss: 0.3838 - val_accuracy: 0.7821 - val_loss: 0.4712
Epoch 91/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8410 - loss: 0.3587 - val_accuracy: 0.7877 - val_loss: 0.4717
Epoch 92/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8187 - loss: 0.4036 - val_accuracy: 0.7821 - val_loss: 0.4702
Epoch 93/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8276 - loss: 0.3803 - val_accuracy: 0.7821 - val_loss: 0.4715
Epoch 94/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8600 - loss: 0.3722 - val_accuracy: 0.7877 - val_loss: 0.4717
Epoch 95/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8435 - loss: 0.3653 - val_accuracy: 0.7821 - val_loss: 0.4738
Epoch 96/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8097 - loss: 0.4063 - val_accuracy: 0.7933 - val_loss: 0.4719
Epoch 97/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8360 - loss: 0.3760 - val_accuracy: 0.7821 - val_loss: 0.4754
Epoch 98/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8121 - loss: 0.4262 - val_accuracy: 0.7821 - val_loss: 0.4755
Epoch 99/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8340 - loss: 0.3747 - val_accuracy: 0.7877 - val_loss: 0.4783
Epoch 100/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8262 - loss: 0.3995 - val_accuracy: 0.7821 - val_loss: 0.4759

In [16]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
model = rf.fit(x_train_ss , y_train)
model.score(x_val_ss , y_val)

0.776536312849162

In [17]:
print(f"Yeni RF Skoru: {rf.score(x_val_ss, y_val)}")

Yeni RF Skoru: 0.776536312849162